In [6]:
import pandas as pd
from funcoes import limpa_vacinas_dados

In [7]:
vacinas_cobertura = pd.read_csv('../dados_brutos/cobertura_vacina_hep.csv', sep=';', na_values=0, usecols=[0,1,2], decimal=',')
vacinas_doses = pd.read_csv('../dados_brutos/vacina_hepatite.csv', sep=';', na_values=0, usecols=[0,1,2])

In [8]:
vacinas_cobertura = limpa_vacinas_dados(vacinas_cobertura, 'Cobertura_vacina_100Hab')
vacinas_doses = limpa_vacinas_dados(vacinas_doses, 'Doses_totais')

In [9]:
vacinas = pd.merge(vacinas_cobertura,vacinas_doses, on=['Ano', 'Classe_viral'], how='outer')
vacinas

     Ano Classe_viral  Cobertura_vacina_100Hab  Doses_totais
0   1994            B                     8.85     2297035.0
1   1995            B                    10.50     2521993.0
2   1996            B                    16.50     2989325.0
3   1997            B                     5.79     2002570.0
4   1998            B                    12.63     8747762.0
5   1999            B                    83.50    23190333.0
6   2000            B                    91.08    16638758.0
7   2001            B                    91.88    35206019.0
8   2002            B                    91.47    30906741.0
9   2003            B                    92.00    24266713.0
10  2004            B                    96.26    17948973.0
11  2005            B                    98.46    17102273.0
12  2006            B                   100.30    15137953.0
13  2007            B                    99.89    14951270.0
14  2008            B                    96.06    14809334.0
15  2009            B                   100.20    14431868.0
16  2010            B                    96.08    14671210.0
17  2011            B                    97.71    16694735.0
18  2012            B                    96.67    15762053.0
19  2013            B                   100.56    15802725.0
20  2014            B                    96.42    15054976.0
21  2015            B                    97.74    11981494.0
22  2016            B                   105.19     7094381.0
23  2017            B                    84.40     8862265.0
24  2018            B                    88.53     8224064.0
25  2019            B                    70.77     8133178.0
26  2020            B                    76.94     5719464.0
27  1994            A                      NaN           NaN
28  1995            A                      NaN           NaN
29  1996            A                      NaN           NaN
30  1997            A                      NaN           NaN
31  1998            A                      NaN           NaN
32  1999            A                      NaN           NaN
33  2000            A                      NaN          38.0
34  2001            A                      NaN       41062.0
35  2002            A                      NaN       58788.0
36  2003            A                      NaN       68883.0
37  2004            A                      NaN       85271.0
38  2005            A                      NaN      100081.0
39  2006            A                      NaN       99674.0
40  2007            A                      NaN      124675.0
41  2008            A                      NaN      157642.0
42  2009            A                      NaN      180828.0
43  2010            A                      NaN      157154.0
44  2011            A                      NaN      199190.0
45  2012            A                      NaN      234009.0
46  2013            A                      NaN      265185.0
47  2014            A                    60.13     1908581.0
48  2015            A                    97.07     2946868.0
49  2016            A                    71.58     2222008.0
50  2017            A                    78.94     2812314.0
51  2018            A                    82.69     2645982.0
52  2019            A                    85.02     2704209.0
53  2020            A                    74.91     2360309.0

In [10]:
vacinas.set_index('Ano').to_csv('../dados_limpos/vacinas_hep')